neurons:
  PhotoInsensitive:
    R1:

    R2:

    R3:

    R4:

    R5:

    R6:

  MorrisLecar:
    L1:

    L2:

    Mi1:
      V_1: -15.0
      V_2: 2.0
      V_3: -45.0
      V_4: 0.8
      phi: 0.0005
      offset: 0
      C: 1
      E_L: -50.0
      E_Ca: 120.0
      E_K: -75.0
      g_L: 0.1
      g_Ca: 2.0
      g_K: 1.0
      V: -55

    Tm1:



synapses:
  InjectCurrent:
    ext-R1:
      presynaptic: None
      postsynaptic: R1
      type: step
    ext-R2:
      presynaptic: None
      postsynaptic: R2
      type: step
    ext-R3:
      presynaptic: None
      postsynaptic: R3
      type: step
    ext-R4:
      presynaptic: None
      postsynaptic: R4
      type: step
    ext-R5:
      presynaptic: None
      postsynaptic: R5
      type: step
    ext-R6:
      presynaptic: None
      postsynaptic: R6
      type: step

  CustomSynapse:
    R1-L1:
      presynaptic: R1
      postsynaptic: L1
      params:

    R2-L1:
      presynaptic: R2
      postsynaptic: L1
      params:

    R3-L1:
      presynaptic: R3
      postsynaptic: L1
      params:

    R4-L1:
      presynaptic: R4
      postsynaptic: L1
      params:

    R5-L1:
      presynaptic: R5
      postsynaptic: L1
      params:

    R6-L1:
      presynaptic: R6
      postsynaptic: L1
      params:


    R1-L2:
      presynaptic: R1
      postsynaptic: L2
      params:

    R2-L2:
      presynaptic: R2
      postsynaptic: L2
      params:

    R3-L2:
      presynaptic: R3
      postsynaptic: L2
      params:

    R4-L2:
      presynaptic: R4
      postsynaptic: L2
      params:

    R5-L2:
      presynaptic: R5
      postsynaptic: L2
      params:

    R6-L2:
      presynaptic: R6
      postsynaptic: L2
      params:

    L1-Mi1:
      presynaptic: L1
      postsynaptic: Mi1
      params:


    L2-Tm1:
      presynaptic: L2
      postsynaptic: Tm1
      params:


times:
  dt: 0.0001
  steps: 10000
